name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar para deploys automáticos
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Configurar o Node.js (caso seu projeto use Node)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Altere conforme a versão que você precisa

    # 3. Instalar dependências
    - name: Install dependencies
      run: npm install

    # 4. Rodar testes (se necessário)
    - name: Run tests
      run: npm test  # Modifique conforme o seu processo de testes

    # 5. Configurar Vercel CLI
    - name: Set up Vercel CLI
      run: |
        curl -fsSL https://vercel.com/download -o vercel-cli.tar.gz
        tar -xvzf vercel-cli.tar.gz
        sudo mv vercel /usr/local/bin/

    # 6. Autenticar com Vercel
    - name: Vercel Authentication
      run: vercel login ${{ secrets.VERCEL_TOKEN }}

    # 7. Fazer o deploy para o Vercel
    - name: Deploy to Vercel
      run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_TEAM }} --confirm

