name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build  # Still depends on the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # Still depends on build & test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Vercel Login (using environment variable)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel login $VERCEL_TOKEN

      - name: Deploy to Vercel (using environment variables)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM: ${{ secrets.VERCEL_TEAM }}  # If deploying to a specific team
        run: vercel --prod --token $VERCEL_TOKEN --scope $VERCEL_TEAM --confirm