name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        run: |
          # Adicionar repositório do Node.js
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          # Instalar Node.js e npm
          sudo apt-get install -y nodejs
          # Verificar as versões do Node.js e npm
          node -v
          npm -v

      - name: Install dependencies
        run: npm install  # Instalar dependências com npm

      - name: Build the application
        run: npm run build  # Build da aplicação

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        run: |
          # Adicionar repositório do Node.js
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          # Instalar Node.js e npm
          sudo apt-get install -y nodejs
          # Verificar as versões do Node.js e npm
          node -v
          npm -v

      - name: Install dependencies
        run: npm install  # Instalar dependências com npm

      - name: Run tests
        run: npm test  # Rodar os testes

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        run: |
          # Adicionar repositório do Node.js
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          # Instalar Node.js e npm
          sudo apt-get install -y nodejs
          # Verificar as versões do Node.js e npm
          node -v
          npm -v

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
