name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Se o package.json estiver na raiz, não é necessário usar "cd"
    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build  # O job de "test" depende que o "build" seja concluído com sucesso

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    needs: [build, test]  # O job de "deploy" só será executado se os jobs de build e test passarem
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Configurar o Vercel CLI e fazer o deploy
    - name: Set up Vercel CLI
      run: |
        curl -fsSL https://vercel.com/download -o vercel-cli.tar.gz
        tar -xvzf vercel-cli.tar.gz
        sudo mv vercel /usr/local/bin/

    - name: Vercel Authentication
      run: vercel login ${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Vercel
      run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_TEAM }} --confirm
