name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Adicionar um comando para listar arquivos e ajudar na depuração
    - name: List files
      run: ls -alh

    # Caso o package.json esteja em uma subpasta, altere o diretório
    - name: Set working directory (se necessário)
      run: cd subpasta

    # Instalar dependências
    - name: Install dependencies
      run: npm install

    # Build do projeto
    - name: Build project
      run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Configurar CLI do Vercel e fazer o deploy
    - name: Set up Vercel CLI
      run: |
        curl -fsSL https://vercel.com/download -o vercel-cli.tar.gz
        tar -xvzf vercel-cli.tar.gz
        sudo mv vercel /usr/local/bin/

    - name: Vercel Authentication
      run: vercel login ${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Vercel
      run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_TEAM }} --confirm
